services:
  - type: web
    name: farmxpert-frontend
    env: static
    plan: free
    buildCommand: "npm install && npm run build"
    staticPublishPath: "build"
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://backend-farmxpert.onrender.com
      - key: REACT_APP_ENV
        value: production