static_sites:
  - name: farmxpert-frontend
    buildCommand: npm install && npm run build
    publicPath: /build
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://backend-farmxpert.onrender.com
      - key: REACT_APP_ENV
        value: production